# Generated by Django 4.2.26 on 2025-11-26 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_open_candle__open'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('session', models.CharField(choices=[('london', 'London'), ('newyork', 'New York'), ('asia', 'Asia')], max_length=20)),
                ('timeframe', models.CharField(choices=[('1m', '1m'), ('3m', '3m'), ('5m', '5m'), ('15m', '15m'), ('1h', '1H'), ('4h', '4H'), ('d', 'D')], max_length=10)),
                ('account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('risk_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('breakeven', 'Break Even')], max_length=10)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('r_multiple', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ict_setup', models.CharField(blank=True, max_length=255)),
                ('higher_tf_bias', models.CharField(blank=True, max_length=20)),
                ('ifvg_used', models.BooleanField(default=False)),
                ('ob_used', models.BooleanField(default=False)),
                ('breaker_used', models.BooleanField(default=False)),
                ('liquidity_sweep_used', models.BooleanField(default=False)),
                ('mitigation_block_used', models.BooleanField(default=False)),
                ('pre_trade_emotion', models.CharField(blank=True, max_length=50)),
                ('post_trade_emotion', models.CharField(blank=True, max_length=50)),
                ('trade_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2)),
                ('followed_plan', models.BooleanField(default=False)),
                ('emotional_trade', models.BooleanField(default=False)),
                ('took_profit_early', models.BooleanField(default=False)),
                ('missed_trade', models.BooleanField(default=False)),
                ('moved_stop_loss', models.BooleanField(default=False)),
                ('revenge_trade', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('stop_levels', models.JSONField(blank=True, default=list)),
                ('take_profit_levels', models.JSONField(blank=True, default=list)),
                ('external_trade_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
