# Generated by Django 4.2.26 on 2025-11-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tradejournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradejournal',
            name='r_multiple',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='risk_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
