# Generated by Django 4.2.26 on 2025-11-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tradejournal_r_multiple_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradejournal',
            name='username',
        ),
    ]
