# Generated by Django 4.2.26 on 2025-11-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tradejournal_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradejournal',
            name='username',
        ),
    ]
