# Generated by Django 4.2.26 on 2025-12-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='course',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
