# Generated by Django 4.2.26 on 2026-01-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_flashcard_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField()),
                ('question', models.TextField()),
                ('official_answer', models.TextField()),
                ('require_keypoints', models.PositiveIntegerField(default=1, help_text='Minimum number of required keypoints to pass')),
                ('pass_score', models.FloatField(default=0.45, help_text='Similarity score required to pass')),
            ],
        ),
    ]
